# Generated by Django 6.0.7 on 2026-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField(default=80)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Example: fa-python, fa-react', max_length=100)),
            ],
        ),
    ]
